---
- hosts: db
  remote_user: ec2-user
  become: yes
  become_method: sudo
  vars_files:
  - secret_variables.yml
  tasks:
  - name: copy repos
    copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0744

# --- Mariadb Client local installation ---
  - name: install maria
    yum: name=MariaDB-client update_cache=yes state=present

  - name: unzip files
    unarchive: src=db/db.tgz dest=~/cit-360/ansible/db/ mode=0740

# --- Run modified bash script to create databases on RDS instance ----
  - name: make database
    command: ./make_databases_new.sh {{ db_password }} {{ endpoint }} {{ db_masteruser }} chdir=/home/ec2-user/cit-360/ansible/db/db
    ignore_errors: True
