---
- hosts: web
  remote_user: root
  become: yes
  become_method: sudo
  vars_files:
  - secret_variables.yml
  vars:
   service_name: curriculum
   service_version: 1.0
   app_env: test
   db_host: main-database-west.cd93nmwqszs2.us-west-2.rds.amazonaws.com
   db_database: curriculum
   db_username: curriculum
   db_port: 3306
   service_dir: /usr/share/nginx/{{ service_name }}
  tasks:
  - name: epel-release install
    yum: name=epel-release update_cache=yes state=present

  - name: Install gcc
    command: yum install -y gcc make

  - name: dependency installation
    yum: name=pcre-devel.x86_64,zlib-devel.x86_64 update_cache=yes state=present

# --- Complete nginx installation ---
  - name: nginx installation
    yum: name=nginx.x86_64 update_cache=yes state=present
    register: nginx_install

# --- Complete php installation ---
  - name: php installation
    yum: name=php.x86_64 update_cache=yes state=present

# --- Install php packages  ---

  - name: ngnix installation
    yum: name=php-fpm.x86_64,php-ldap.x86_64,php-mbstring.x86_64,php-mcrypt.x86_64,php-mysql.x86_64  update_cache=yes state=present

# --- download composer file as composer.php with chmod 755 permission ---
  - name: Donwload composer
    get_url:
     url: https://getcomposer.org/installer
     dest: /tmp/composer.php
     mode: 0755

# --- Install composer.php from tmp ---
  - name: Install composer
    command: php composer.php chdir=/tmp
# --- move install composer.phar file to bin for global access ---
  - name: Move Composer installation files
    command: mv /tmp/composer.phar /usr/local/bin

# --- copying configuration files block ----
  - name: copy ngnix configuration files
    copy: src=web/nginx.conf dest=/etc/nginx/ mode=0744
    register: nginx_conf

  - name: copy host configuration files
    template: src=web/vhost.conf.j2 dest=/etc/nginx/conf.d/{{ service_name }}.conf mode=0744
    register: vhost_conf

  - name: copy php configuration files
    template: src=web/php.ini.j2 dest=/etc/php.ini mode=0744
    register: php_conf

  - name: copy php-fpm configuration files
    copy: src=web/php-fpm-web.conf dest=/etc/php-fpm.d/www.conf mode=0744
    register: php_fpm_conf
# ------------------------------------------
  - name: start nginx service
    service: name=nginx state=restarted enabled=yes
    when: nginx_install|changed or nginx_conf|changed or vhost_conf|changed

  - name: start php-fpm service
    service: name=php-fpm state=restarted enabled=yes
    when: nginx_install|changed or php_conf|changed or php_fpm_conf|changed

  - name: make Curriculum directory
    file: path={{ service_dir }} state=directory

  - name: untarzip service files to server
    unarchive: src=web/{{ service_name }}.tgz dest={{ service_dir }} mode=0755

  - name: composer update
    command: chdir={{ service_dir }} /usr/local/bin/composer.phar update

# --- give read write execute access to everyone ----
  - name: chmod 777 storage
    file: path={{ service_dir }}/storage state=directory mode=0777 recurse=yes

  - name: Permission of ngnix files
    file: path={{ service_dir }} owner=nginx group=nginx state=directory recurse=yes

  - name: run template
    template: src=web/env.j2 dest={{ service_dir }}/.env mode=0744 owner=nginx
